<a href="https://colab.research.google.com/github/K0SATIN/Old_Cursach/blob/master/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Сколько уже можно тянуть, давай начнём!')

In [30]:
import numpy as np
def array_output(a):
  print()
  print(a)

In [31]:

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 50)
e = np.arange(10, 50, 2)
f = np.arange(0, 9)
f.resize(3,3)
g = np.random.random()
h = np.random.normal(0, 1, 15)
i = np.arange(0.01, 1+0.01, 0.01)
i.resize(10,10)

In [32]:
mat = np.arange(1,26).reshape(5,5)
array_output(mat)
array_output(mat[2:, 1:])
array_output(mat[3, 4])
array_output(mat[:3, 1])
array_output(mat[4:, :])
array_output(mat[3:, :])
array_output(mat.sum())
array_output(np.std(mat))
array_output(mat.sum(axis = 0))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]

20

[ 2  7 12]

[[21 22 23 24 25]]

[[16 17 18 19 20]
 [21 22 23 24 25]]

325

7.211102550927978

[55 60 65 70 75]
